
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 63936
 */
public class Batch1 extends javax.swing.JFrame {

    private int productPk = 0;
    private int totalQuantity = 0;

    // Constructor for the Batch1 class.
    public Batch1() {
        // Initialize the components of the JFrame (UI elements).
        initComponents();

        // Set the JFrame to appear at the center of the screen.
        setLocationRelativeTo(null);

        // Center-align the text in the table cells.
        centerTableText();

        // Center-align the text in the table header (column titles).
        centerTableHeader();
    }

// Method to center-align the text in all cells of the table.
    private void centerTableText() {
        // Create a cell renderer with center alignment.
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Loop through all columns of the table and apply the center renderer.
        for (int i = 0; i < tableBatch1.getColumnCount(); i++) {
            tableBatch1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

// Method to center-align the text in the table header (column titles).
    private void centerTableHeader() {
        // Get the table header object.
        JTableHeader header = tableBatch1.getTableHeader();

        // Get the default renderer for the table header.
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();

        // Set the header renderer to center-align the text.
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Apply the modified renderer back to the table header.
        header.setDefaultRenderer(headerRenderer);
    }

// Method to validate input fields based on the form type ("edit" or "new").
    private boolean validateFields(String formType) {
        // Check if the form type is "edit".
        if (formType.equals("edit")
                && !txtName.getText().equals("") // Ensure "name" field is not empty.
                && !txtPrice.getText().equals("") // Ensure "price" field is not empty.
                && !txtExpirationDate.getText().equals("")) { // Ensure "expirationDate" field is not empty.
            return false; // Fields are valid, so return false (no validation error).
        } // Check if the form type is "new".
        else if (formType.equals("new")
                && !txtName.getText().equals("") // Ensure "name" field is not empty.
                && !txtPrice.getText().equals("") // Ensure "price" field is not empty.
                && !txtExpirationDate.getText().equals("") // Ensure "expirationDate" field is not empty.
                && !txtQuantity.getText().equals("")) { // Ensure "quantity" field is not empty.
            return false; // Fields are valid, so return false (no validation error).
        } // If any required field is empty, return true to indicate a validation error.
        else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBatch1 = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblExpiration = new javax.swing.JLabel();
        txtExpirationDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/All_page_Background.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setBackground(new java.awt.Color(0, 20, 82));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 69, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 20, 82));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        btnReset.setBackground(new java.awt.Color(0, 20, 82));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Delete");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, -1));

        btnClose.setBackground(new java.awt.Color(204, 0, 0));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 70, -1));

        tableBatch1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tableBatch1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price", "Expiration Date"
            }
        ));
        tableBatch1.setRowHeight(30);
        tableBatch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBatch1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBatch1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, 820, 210));

        lblName.setFont(new java.awt.Font("Powerhouse Sans", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        lblName.setToolTipText("");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        txtName.setFont(new java.awt.Font("Powerhouse Sans", 1, 18)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 320, -1));

        lblQuantity.setFont(new java.awt.Font("Powerhouse Sans", 0, 18)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quantity");
        lblQuantity.setToolTipText("");
        jPanel1.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        txtQuantity.setFont(new java.awt.Font("Powerhouse Sans", 1, 18)); // NOI18N
        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 320, -1));

        lblPrice.setFont(new java.awt.Font("Powerhouse Sans", 0, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Price");
        lblPrice.setToolTipText("");
        jPanel1.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        txtPrice.setFont(new java.awt.Font("Powerhouse Sans", 1, 18)); // NOI18N
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 320, -1));

        lblExpiration.setFont(new java.awt.Font("Powerhouse Sans", 0, 18)); // NOI18N
        lblExpiration.setForeground(new java.awt.Color(255, 255, 255));
        lblExpiration.setText("Expiration Date");
        lblExpiration.setToolTipText("");
        jPanel1.add(lblExpiration, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        txtExpirationDate.setFont(new java.awt.Font("Powerhouse Sans", 1, 18)); // NOI18N
        txtExpirationDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExpirationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpirationDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 320, -1));

        jLabel1.setFont(new java.awt.Font("Powerhouse Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BATCH 2");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        // Cast the table model to DefaultTableModel to allow adding rows dynamically.
        DefaultTableModel model = (DefaultTableModel) tableBatch1.getModel();

        try {
            // Establish a connection to the database using a custom connection method.
            Connection con = MyConnection.getConnection();

            // Create a Statement object to execute SQL queries.
            Statement st = con.createStatement();

            // Execute a query to retrieve all records from the "batch" table.
            ResultSet rs = st.executeQuery("SELECT * FROM batch");

            // Iterate through the result set to fetch each row.
            while (rs.next()) {
                // Add a row to the table model with the retrieved data.
                model.addRow(new Object[]{
                    rs.getString("name"), // Get the "name" column value.
                    rs.getString("quantity"), // Get the "quantity" column value.
                    rs.getString("price"), // Get the "price" column value.
                    rs.getString("expirationDate") // Get the "expirationDate" column value.
                });
            }
        } catch (Exception e) {
            // If an exception occurs, show an error message dialog.
            JOptionPane.showMessageDialog(null, e);
        }

        // Disable the "Update" button by default to prevent unwanted user interactions.
        btnUpdate.setEnabled(false);

    }//GEN-LAST:event_formComponentShown

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        try (Connection con = MyConnection.getConnection()) {

            // Get the selected row index in the JTable
            DefaultTableModel model = (DefaultTableModel) tableBatch1.getModel();
            int selectedRow = tableBatch1.getSelectedRow();

            // If no row is selected, show a message and return
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            String name = model.getValueAt(selectedRow, 0).toString();
            String quantity = model.getValueAt(selectedRow, 1).toString();

            // Get the values from the selected row (assuming the client_name and file_link are in columns 0 and 1)
            // SQL query to delete the row from the database based on client_name and file_link
            String sql = "DELETE FROM batch WHERE name=? AND quantity=?";

            // Prepare the SQL statement
            try (PreparedStatement stmt = con.prepareStatement(sql)) {
                stmt.setString(1, name);
                stmt.setString(2, quantity);

                // Set client_name value
                // Set file_link value
                // Execute the update (deletion)
                int rowsAffected = stmt.executeUpdate();

                // If rows are affected, proceed to remove the row from the table
                if (rowsAffected > 0) {
                    // Remove the selected row from the table model
                    model.removeRow(selectedRow);

                    // Show success message
                    JOptionPane.showMessageDialog(null, "Row deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // If no rows were deleted from the database
                    JOptionPane.showMessageDialog(null, "Error deleting the row from the database.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Database connection error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        setVisible(false);
        new Batch1().setVisible(true);

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // Get the value of the name field from the text box.
        String name = txtName.getText();

        // Get the value of the quantity field from the text box.
        String quantity = txtQuantity.getText();

        // Get the value of the price field from the text box.
        String price = txtPrice.getText();

        // Get the value of the expiration date field from the text box.
        String expirationDate = txtExpirationDate.getText();

        // Validate input fields using a custom validation method.
        // If the validation fails, display an error message to the user.
        if (validateFields("new")) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                // Establish a connection to the database using a custom connection method.
                Connection con = MyConnection.getConnection();

                // Prepare an SQL query to insert the product details into the "batch" table.
                PreparedStatement ps = con.prepareStatement(
                        "INSERT INTO batch (name, quantity, price, expirationDate) VALUES (?, ?, ?, ?)"
                );

                // Set the parameters for the prepared statement.
                ps.setString(1, name);           // Set the value for the "name" column.
                ps.setString(2, quantity);       // Set the value for the "quantity" column.
                ps.setString(3, price);          // Set the value for the "price" column.
                ps.setString(4, expirationDate); // Set the value for the "expirationDate" column.

                // Execute the SQL query to insert the data into the database.
                ps.executeUpdate();

                // Notify the user that the product was added successfully.
                JOptionPane.showMessageDialog(null, "Product Added Successfully");

                // Close the current window.
                setVisible(false);

                // Open a new window for the "Batch1" class (refresh or reload functionality).
                new Batch1().setVisible(true);
            } catch (Exception e) {
                // If an exception occurs, show an error message dialog with the exception details.
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tableBatch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBatch1MouseClicked
        // TODO add your handling code here
        // Get the index of the selected row in the table.
        int index = tableBatch1.getSelectedRow();

        // Get the table's data model to access the cell values.
        TableModel model = tableBatch1.getModel();

        // Retrieve the "name" value from the first column (index 0) of the selected row and convert it to a string.
        String name = model.getValueAt(index, 0).toString();

        // Set the retrieved "name" value into the txtName text field for editing.
        txtName.setText(name);

        // Retrieve the "quantity" value from the second column (index 1) of the selected row and convert it to a string.
        String quantity = model.getValueAt(index, 1).toString();

        // Update the lblQuantity label text to indicate "Add Quantity" for clarity.
        lblQuantity.setText("Add Quantity");

        // Retrieve the "price" value from the third column (index 2) of the selected row and convert it to a string.
        String price = model.getValueAt(index, 2).toString();

        // Set the retrieved "price" value into the txtPrice text field for editing.
        txtPrice.setText(price);

        // Retrieve the "expirationDate" value from the fourth column (index 3) of the selected row and convert it to a string.
        String expirationDate = model.getValueAt(index, 3).toString();

        // Set the retrieved "expirationDate" value into the txtExpirationDate text field for editing.
        txtExpirationDate.setText(expirationDate);

        // Disable the "Save" button to prevent adding a new record while editing.
        btnSave.setEnabled(false);

        // Enable the "Update" button to allow saving changes to the selected record.
        btnUpdate.setEnabled(true);


    }//GEN-LAST:event_tableBatch1MouseClicked

    private void txtExpirationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpirationDateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtExpirationDateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // Retrieve the values entered in the text fields.
       String name = txtName.getText();
        String quantity = txtQuantity.getText();
        String price = txtPrice.getText();
        String expirationDate = txtExpirationDate.getText();

// Ensure that all required fields are filled in.
        if (validateFields("edit")) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                // Parse the quantity value as an integer.
                int newQuantity = Integer.parseInt(quantity);

                // Establish a connection to the database.
                Connection con = MyConnection.getConnection();

                // Prepare an SQL update query to modify the selected product details.
                // This query will only update the product that matches the selected "name".
                PreparedStatement ps = con.prepareStatement(
                        "UPDATE batch SET quantity = quantity + ?, price = ?, expirationDate = ? WHERE name = ?"
                );

                // Set the values for the placeholders in the prepared statement.
                ps.setInt(1, newQuantity); // Add the new quantity to the current quantity in the database.
                ps.setString(2, price); // Set the new price in the database.
                ps.setString(3, expirationDate); // Set the new expiration date in the database.
                ps.setString(4, name); // Specify the product to update by name.

                // Execute the update query.
                int rowsUpdated = ps.executeUpdate();

                if (rowsUpdated > 0) {
                    // If the update is successful, display a success message.
                    JOptionPane.showMessageDialog(null, "Product Updated Successfully");

                    // Close the current window and open a new instance of Batch2 to refresh the UI.
                    setVisible(false);
                    new Batch1().setVisible(true);
                } else {
                    // If no rows were updated, notify the user (e.g., product not found).
                    JOptionPane.showMessageDialog(null, "No product found with the specified name.");
                }

            } catch (NumberFormatException e) {
                // If the quantity is not a valid number, catch the exception and show an error message.
                JOptionPane.showMessageDialog(null, "Invalid quantity format. Please enter a numeric value.");
            } catch (Exception e) {
                // If any other exception occurs, display the error message.
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batch1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batch1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batch1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batch1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batch1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExpiration;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTable tableBatch1;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
