
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.JTableHeader;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 63936
 */
public class ManageProduct extends javax.swing.JFrame {
// Declare a variable to store the current quantity of the product.

    private int currentQuantity = 0;

    /**
     * Constructor for the ManageProduct form.
     */
    public ManageProduct() {
        // Initialize components (auto-generated by the GUI builder).
        initComponents();

        // Set the location of the form to the center of the screen.
        setLocationRelativeTo(null);

        // Center the text in the table cells.
        centerTableText();

        // Center the text in the table header.
        centerTableHeader();
    }

    /**
     * Method to center text in the table cells.
     */
    private void centerTableText() {
        // Create a cell renderer for centering text.
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER); // Align text to center.

        // Loop through each column in the table and apply the renderer.
        for (int i = 0; i < tableProduct.getColumnCount(); i++) {
            tableProduct.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    /**
     * Method to center text in the table header.
     */
    private void centerTableHeader() {
        // Get the header of the table.
        JTableHeader header = tableProduct.getTableHeader();

        // Create a renderer for centering header text.
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER); // Align header text to center.

        // Apply the renderer to the table header.
        header.setDefaultRenderer(headerRenderer);
    }

    /**
     * Method to validate fields based on the form type.
     *
     * @param formType - The type of form ("edit" or "new").
     * @return - `true` if validation fails (fields are missing), `false` if
     * validation passes.
     */
    private boolean validateFields(String formType) {
        // Validation for "edit" form: Check if name, price, and expiration date are filled in.
        if (formType.equals("edit")
                && !txtName.getText().equals("")
                && !txtPrice.getText().equals("")
                && !txtExpirationDate.getText().equals("")) {
            return false; // Fields are valid, no error.
        } else {
            // Validation for "new" form: Check if name, price, expiration date, and quantity are filled in.
            return !(formType.equals("new")
                    && !txtName.getText().equals("")
                    && !txtPrice.getText().equals("")
                    && !txtExpirationDate.getText().equals("")
                    && !txtQuantity.getText().equals(""));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtExpirationDate = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/All_page_Background.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Powerhouse Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BATCH 1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        lblName.setFont(new java.awt.Font("Powerhouse Sans", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, 20));

        lblQuantity.setFont(new java.awt.Font("Powerhouse Sans", 0, 18)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quantity");
        jPanel2.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, 20));

        lblPrice.setFont(new java.awt.Font("Powerhouse Sans", 0, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Price");
        jPanel2.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, 20));

        lblExpirationDate.setFont(new java.awt.Font("Powerhouse Sans", 0, 18)); // NOI18N
        lblExpirationDate.setForeground(new java.awt.Color(255, 255, 255));
        lblExpirationDate.setText("Expiration Date");
        jPanel2.add(lblExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, 20));

        btnSave.setBackground(new java.awt.Color(0, 20, 82));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 20, 82));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 80, -1));

        btnReset.setBackground(new java.awt.Color(0, 20, 82));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Delete");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, -1, -1));

        btnClose.setBackground(new java.awt.Color(204, 0, 0));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, -1));

        txtExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtExpirationDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExpirationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpirationDateActionPerformed(evt);
            }
        });
        jPanel2.add(txtExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 320, -1));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 320, -1));

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel2.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 320, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 320, -1));

        tableProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price", "Expiration Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableProduct.setGridColor(new java.awt.Color(255, 255, 255));
        tableProduct.setRowHeight(30);
        tableProduct.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tableProduct.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProduct);
        if (tableProduct.getColumnModel().getColumnCount() > 0) {
            tableProduct.getColumnModel().getColumn(0).setResizable(false);
            tableProduct.getColumnModel().getColumn(1).setResizable(false);
            tableProduct.getColumnModel().getColumn(2).setResizable(false);
            tableProduct.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 830, 220));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        // Get the table model for the "tableProduct".
        DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();

        try {
            // Establish a connection to the database.
            Connection con = MyConnection.getConnection();

            // Create a statement object to execute SQL queries.
            Statement st = con.createStatement();

            // Execute a query to fetch all rows from the "product" table.
            ResultSet rs = st.executeQuery("select * from product");

            // Iterate through the result set to process each row.
            while (rs.next()) {
                // Add a new row to the table model with the fetched data.
                // Each column is retrieved using the column name from the database.
                model.addRow(new Object[]{
                    rs.getString("name"), // Get the product name.
                    rs.getString("quantity"), // Get the product quantity.
                    rs.getString("price"), // Get the product price.
                    rs.getString("expirationDate") // Get the product expiration date.
                });
            }
        } catch (Exception e) {
            // Display an error message if an exception occurs during database interaction.
            JOptionPane.showMessageDialog(null, e);
        }

        // Disable the "Update" button by default since no product is selected initially.
        btnUpdate.setEnabled(false);

    }//GEN-LAST:event_formComponentShown

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        try (Connection con = MyConnection.getConnection()) {

            // Get the selected row index in the JTable
            DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();
            int selectedRow = tableProduct.getSelectedRow();

            // If no row is selected, show a message and return
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String name = model.getValueAt(selectedRow, 0).toString();
            String quantity = model.getValueAt(selectedRow, 1).toString();

            // Get the values from the selected row (assuming the client_name and file_link are in columns 0 and 1)
            // SQL query to delete the row from the database based on client_name and file_link
            String sql = "DELETE FROM product WHERE name=? AND quantity=?";

            // Prepare the SQL statement
            try (PreparedStatement stmt = con.prepareStatement(sql)) {
                stmt.setString(1, name);
                stmt.setString(2, quantity);

                // Set client_name value
                // Set file_link value
                // Execute the update (deletion)
                int rowsAffected = stmt.executeUpdate();

                // If rows are affected, proceed to remove the row from the table
                if (rowsAffected > 0) {
                    // Remove the selected row from the table model
                    model.removeRow(selectedRow);

                    // Show success message
                    JOptionPane.showMessageDialog(null, "Row deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // If no rows were deleted from the database
                    JOptionPane.showMessageDialog(null, "Error deleting the row from the database.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Database connection error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
        setVisible(false);
        new ManageProduct().setVisible(true);


    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // Retrieve values from the input fields.
        String name = txtName.getText();                  // Get the product name from the text field.
        String quantity = txtQuantity.getText();          // Get the product quantity from the text field.
        String price = txtPrice.getText();                // Get the product price from the text field.
        String expirationDate = txtExpirationDate.getText(); // Get the product expiration date from the text field.

// Check if all fields are filled before proceeding.
        if (validateFields("new")) {
            // Display an error message if any field is empty.
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                // Establish a connection to the database.
                Connection con = MyConnection.getConnection();

                // Prepare an SQL query to insert data into the "product" table.
                PreparedStatement ps = con.prepareStatement(
                        "insert into product (name,quantity,price,expirationDate) values (?,?,?,?)"
                );

                // Set the parameters for the prepared statement.
                ps.setString(1, name);          // Set the "name" value.
                ps.setString(2, quantity);      // Set the "quantity" value.
                ps.setString(3, price);         // Set the "price" value.
                ps.setString(4, expirationDate); // Set the "expirationDate" value.

                // Execute the query to insert the data into the database.
                ps.executeUpdate();

                // Notify the user that the product was added successfully.
                JOptionPane.showMessageDialog(null, "Product Added Successfully");

                // Close the current form and open a new "ManageProduct" form to refresh the data.
                setVisible(false);
                new ManageProduct().setVisible(true);
            } catch (Exception e) {
                // Display an error message if any exception occurs.
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void tableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductMouseClicked
        // TODO add your handling code here:
        // Get the index of the selected row in the table.
        int index = tableProduct.getSelectedRow(); // Retrieves the index of the currently selected row in the table.

// Get the table model to access the data.
        TableModel model = tableProduct.getModel(); // Fetch the table model to access the values in the table.

// Retrieve the "name" value from the selected row and set it to the text field.
        String name = model.getValueAt(index, 0).toString(); // Get the value of the "name" column (first column) from the selected row.
        txtName.setText(name); // Set the retrieved "name" value in the corresponding text field.

// Retrieve the "quantity" value from the selected row.
        String quantity = model.getValueAt(index, 1).toString(); // Get the value of the "quantity" column (second column) from the selected row.

// Update the label to indicate adding more quantity.
        lblQuantity.setText("Add Quantity"); // Change the label text to indicate that the quantity can be adjusted or added.

// Retrieve the "price" value from the selected row and set it to the text field.
        String price = model.getValueAt(index, 2).toString(); // Get the value of the "price" column (third column) from the selected row.
        txtPrice.setText(price); // Set the retrieved "price" value in the corresponding text field.

// Retrieve the "expirationDate" value from the selected row and set it to the text field.
        String expirationDate = model.getValueAt(index, 3).toString(); // Get the value of the "expirationDate" column (fourth column) from the selected row.
        txtExpirationDate.setText(expirationDate); // Set the retrieved "expirationDate" value in the corresponding text field.

// Disable the "Save" button, as we're updating an existing product.
        btnSave.setEnabled(false); // Disable the Save button to prevent adding a new product during an update operation.

// Enable the "Update" button to allow saving the changes to the selected product.
        btnUpdate.setEnabled(true); // Enable the Update button for updating the selected product.


    }//GEN-LAST:event_tableProductMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
       String name = txtName.getText();
        String quantity = txtQuantity.getText();
        String price = txtPrice.getText();
        String expirationDate = txtExpirationDate.getText();

// Ensure that all required fields are filled in.
        if (validateFields("edit")) {
            JOptionPane.showMessageDialog(null, "All fields are required");
        } else {
            try {
                // Parse the quantity value as an integer.
                int newQuantity = Integer.parseInt(quantity);

                // Establish a connection to the database.
                Connection con = MyConnection.getConnection();

                // Prepare an SQL update query to modify the selected product details.
                // This query will only update the product that matches the selected "name".
                PreparedStatement ps = con.prepareStatement(
                        "UPDATE product SET quantity = quantity + ?, price = ?, expirationDate = ? WHERE name = ?"
                );

                // Set the values for the placeholders in the prepared statement.
                ps.setInt(1, newQuantity); // Add the new quantity to the current quantity in the database.
                ps.setString(2, price); // Set the new price in the database.
                ps.setString(3, expirationDate); // Set the new expiration date in the database.
                ps.setString(4, name); // Specify the product to update by name.

                // Execute the update query.
                int rowsUpdated = ps.executeUpdate();

                if (rowsUpdated > 0) {
                    // If the update is successful, display a success message.
                    JOptionPane.showMessageDialog(null, "Product Updated Successfully");

                    // Close the current window and open a new instance of Batch2 to refresh the UI.
                    setVisible(false);
                    new ManageProduct().setVisible(true);
                } else {
                    // If no rows were updated, notify the user (e.g., product not found).
                    JOptionPane.showMessageDialog(null, "No product found with the specified name.");
                }

            } catch (NumberFormatException e) {
                // If the quantity is not a valid number, catch the exception and show an error message.
                JOptionPane.showMessageDialog(null, "Invalid quantity format. Please enter a numeric value.");
            } catch (Exception e) {
                // If any other exception occurs, display the error message.
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtExpirationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpirationDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpirationDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTable tableProduct;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
